export const info = {
    name: 'mymemory',
    icon: 'logo/mymemory.svg',
};

export enum Language {
    auto = 'auto',
    zh_cn = 'zh-CN',
    zh_tw = 'zh-TW',
    ja = 'ja',
    en = 'en',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt-PT',
    pt_br = 'pt-BR',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    mn_cy = 'mn',
    km = 'km',
    nb_no = 'nb',
    nn_no = 'nn',
    fa = 'fa',
    uk = 'uk',
}
